// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewTweet struct {
	Title  string `json:"title"`
	Body   string `json:"body"`
	UserID string `json:"userId"`
}
